In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras

In [29]:
df = pd.read_csv('TravelInsurancePrediction.csv')
df.head()

Unnamed: 0  Age               Employment Type GraduateOrNot  AnnualIncome  \
0           0   31             Government Sector           Yes        400000   
1           1   31  Private Sector/Self Employed           Yes       1250000   
2           2   34  Private Sector/Self Employed           Yes        500000   
3           3   28  Private Sector/Self Employed           Yes        700000   
4           4   28  Private Sector/Self Employed           Yes        700000   

   FamilyMembers  ChronicDiseases FrequentFlyer EverTravelledAbroad  \
0              6                1            No                  No   
1              7                0            No                  No   
2              4                1            No                  No   
3              3                1            No                  No   
4              8                1           Yes                  No   

   TravelInsurance  
0                0  
1                0  
2                1  
3                0  
4                0

In [30]:
data = df[["Age","TravelInsurance","ChronicDiseases"]]
data.head()

Age  TravelInsurance  ChronicDiseases
0   31                0                1
1   31                0                0
2   34                1                1
3   28                0                1
4   28                0                1

In [31]:
data.isnull().sum()

Age                0
TravelInsurance    0
ChronicDiseases    0
dtype: int64

In [32]:
x=data[["Age","ChronicDiseases"]]
y=data["TravelInsurance"]

In [33]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [34]:
x_train_scaled = x_train.copy()
x_train_scaled["Age"]=x_train["Age"]/100

x_test_scaled = x_test.copy()
x_test_scaled["Age"]=x_test["Age"]/100


In [21]:
x_test_scaled

Age  ChronicDiseases
964   0.33                1
518   0.29                0
421   0.28                0
1434  0.34                0
897   0.31                1
...    ...              ...
1921  0.31                0
757   0.27                1
356   0.34                0
163   0.32                0
1609  0.27                1

[398 rows x 2 columns]

In [69]:
model = keras.models.Sequential([
    keras.layers.Dense(1,activation="sigmoid",kernel_initializer='ones',bias_initializer='zeros')
])
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)
model.fit(x_train_scaled,y_train,epochs=100)

Epoch 1/100
50/50 ━━━━━━━━━━━━━━━━━━━━ 1s 805us/step - accuracy: 0.3527 - loss: 0.8360 
Epoch 2/100
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 700us/step - accuracy: 0.3498 - loss: 0.8101
Epoch 3/100
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 686us/step - accuracy: 0.3494 - loss: 0.7912
Epoch 4/100
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 667us/step - accuracy: 0.3368 - loss: 0.7809
Epoch 5/100
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 623us/step - accuracy: 0.3501 - loss: 0.7601
Epoch 6/100
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 626us/step - accuracy: 0.5210 - loss: 0.7456
Epoch 7/100
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 569us/step - accuracy: 0.5876 - loss: 0.7280
Epoch 8/100
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 661us/step - accuracy: 0.5916 - loss: 0.7132
Epoch 9/100
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 690us/step - accuracy: 0.5969 - loss: 0.6996
Epoch 10/100
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 642us/step - accuracy: 0.5863 - loss: 0.6934
Epoch 11/100
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 636us/step - accuracy: 0.5852 - loss: 0.6870
Epoch 12/100
50/50 ━━━━━━━━━━━━━━━━━━━━ 

In [70]:
model.evaluate(x_test_scaled,y_test)

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 768us/step - accuracy: 0.5847 - loss: 0.6904


[0.6794466376304626, 0.6005024909973145]

In [71]:
x_test_scaled

Age  ChronicDiseases
621   0.28                0
143   0.26                0
1871  0.34                0
1272  0.33                0
1353  0.33                0
...    ...              ...
1507  0.27                0
1537  0.29                0
1045  0.28                1
339   0.29                0
926   0.34                0

[398 rows x 2 columns]

In [72]:
model.predict(x_test_scaled)

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 


array([[0.33820325],
       [0.33658263],
       [0.3430879 ],
       [0.34227145],
       [0.34227145],
       [0.33820325],
       [0.339015  ],
       [0.36711317],
       [0.34227145],
       [0.3430879 ],
       [0.3696433 ],
       [0.33658263],
       [0.37048826],
       [0.3430879 ],
       [0.3430879 ],
       [0.36627147],
       [0.339015  ],
       [0.36795574],
       [0.33820325],
       [0.34390533],
       [0.33820325],
       [0.3430879 ],
       [0.33820325],
       [0.33658263],
       [0.33577377],
       [0.33820325],
       [0.3430879 ],
       [0.33739248],
       [0.34064135],
       [0.33739248],
       [0.37048826],
       [0.33739248],
       [0.33820325],
       [0.33739248],
       [0.36795574],
       [0.3654305 ],
       [0.33658263],
       [0.37048826],
       [0.34064135],
       [0.339015  ],
       [0.34064135],
       [0.37218058],
       [0.33820325],
       [0.339015  ],
       [0.34064135],
       [0.34064135],
       [0.34064135],
       [0.373

In [79]:
x_test_scaled

Age  ChronicDiseases
621   0.28                0
143   0.26                0
1871  0.34                0
1272  0.33                0
1353  0.33                0
...    ...              ...
1507  0.27                0
1537  0.29                0
1045  0.28                1
339   0.29                0
926   0.34                0

[398 rows x 2 columns]

In [80]:
coef,intercept = model.get_weights()
coef,intercept

(array([[0.36246434],
        [0.1303147 ]], dtype=float32),
 array([-0.77280134], dtype=float32))

In [81]:
import math
def sigmoid(arg):
    return 1/(1+math.exp(-arg))

sigmoid(100)
    

1.0

In [82]:
def prediction_function(ages,disease):
    weighted_sum = coef[0]*ages + coef[1]*disease + intercept
    return sigmoid(weighted_sum)

In [83]:
prediction_function(.47,1)

C:\Users\shahabuddin akhon hr\AppData\Local\Temp\ipykernel_9420\3287475515.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-arg))


0.3841126058149413

In [84]:
def log_loss(y_true,y_pred):
    epsilon=1e-8
    y_predication = [max(i,epsilon) for i in y_pred ]
    y_predication_new = [min(i,1-epsilon) for i in y_predication ]
    return -np.mean(y_true*np.log(y_predication_new) + (1-y_true)*np.log(y_predication_new))

In [85]:
import math
def sigmoid_array(arg):
    return 1/(1+np.exp(-arg))


In [86]:
def gradient_descent(age,disease,y_true,iterations):
    w1=w2=1
    bias=0
    rate=0.5
    n=len(age)
    for i in range(iterations):
        weighted_sum = w1*age + w2*disease + bias
        y_pred = sigmoid_array(weighted_sum)
        loss = log_loss(y_true, y_pred)
        
        w1d = (1/n)*np.dot(np.transpose(age),(y_pred - y_true))
        w2d = (1/n)*np.dot(np.transpose(disease),(y_pred - y_true))
        bias_d = np.mean(y_pred - y_true)
        
        w1 = w1 - rate*w1d
        w2 = w2 - rate*w2d
        bias = bias - rate*bias_d
        
        # print(f"w1: {w1}, w2d: {w2}, bias: {bias} loss: {loss}")
        if loss <= 0.4:
            break
        
    return w1,w2,bias
        
    

In [90]:
w1,w2,bias=gradient_descent(x_train_scaled["Age"],x_train_scaled["ChronicDiseases"],y_train,50)

def prediction_function_manual(ages,disease):
    weighted_sum = w1*ages + w2*disease + bias
    return sigmoid(weighted_sum)

prediction_function_manual(.23,1)

0.38266720790269143